try {
  // throw new Error('a');
} catch (e) {
  throw e;
} finally {
  console.log('finally');
}
